apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application-1
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Sarang095/DTAK-Project.git
    targetRevision: HEAD
    path: manifests/
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

