default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: postgres-service  # This should match the service name in docker-compose.yml

development:
  <<: *default
  database: budgy_development

test:
  <<: *default
  database: budgy_test

production:
  <<: *default
  database: budgy_production
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
